# RC Car Dual Raspberry Pi Configuration
# 듀얼 라즈베리파이 RC카 설정

network:
  # Network settings - 네트워크 설정
  controller_ip: "192.168.1.50"    # Controller Pi IP - 컨트롤러 파이 IP
  vehicle_ip: "192.168.1.100"      # Vehicle Pi IP - 차량 파이 IP
  control_port: 8888               # Socket communication port - 제어 통신 포트
  camera_port: 8080                # Camera streaming port - 카메라 스트리밍 포트

controller:
  # Controller settings - 컨트롤러 설정
  gamepad:
    type: "ShanWan"                # Gamepad type - 게임패드 타입
    update_rate: 20                # Hz - 업데이트 주파수
    
  bmw_gear:
    enabled: true                  # Enable BMW gear lever - BMW 기어봉 활성화
    can_interface: "can0"          # CAN interface - CAN 인터페이스
    can_bitrate: 500000            # CAN bitrate - CAN 전송속도
    timeout: 300                   # ms - 기어 변경 간격 (밀리초)
  
  safety:
    connection_timeout: 1.0        # seconds - 연결 타임아웃 (초)
    max_retry_attempts: 5          # 최대 재시도 횟수

vehicle:
  # Vehicle settings - 차량 설정
  piracer:
    max_throttle: 1.0              # Maximum throttle (0.0-1.0) - 최대 스로틀
    max_steering: 1.0              # Maximum steering (0.0-1.0) - 최대 조향
    
  gear_limits:
    # Speed limits by gear - 기어별 속도 제한
    P: 0.0      # Park - 주차
    N: 0.0      # Neutral - 중립
    R: 0.4      # Reverse (40%) - 후진 (40%)
    D: 1.0      # Drive (100%) - 전진 (100%)
    M1: 0.25    # Manual 1 (25%) - 수동 1단 (25%)
    M2: 0.5     # Manual 2 (50%) - 수동 2단 (50%)
    M3: 0.75    # Manual 3 (75%) - 수동 3단 (75%)
    M4: 1.0     # Manual 4 (100%) - 수동 4단 (100%)
    M5: 1.0     # Manual 5 (100%) - 수동 5단 (100%)
    M6: 1.0     # Manual 6 (100%) - 수동 6단 (100%)
    M7: 1.0     # Manual 7 (100%) - 수동 7단 (100%)
    M8: 1.0     # Manual 8 (100%) - 수동 8단 (100%)
  
  safety:
    emergency_stop: true           # Enable emergency stop - 비상정지 활성화  
    timeout_stop: 1.0              # seconds - 타임아웃 정지 시간
    connection_timeout: 2.0        # seconds - 연결 타임아웃

camera:
  # Camera settings - 카메라 설정
  resolution:
    width: 640                     # Frame width - 프레임 너비
    height: 480                    # Frame height - 프레임 높이
  
  streaming:
    fps: 30                        # Frames per second - 초당 프레임
    quality: 85                    # JPEG quality (0-100) - JPEG 품질
    enable_overlay: true           # Show timestamp and info - 정보 오버레이 표시
  
  camera_type: "auto"              # auto, picamera2, usb - 카메라 타입

dashboard:
  # Dashboard settings - 대시보드 설정
  enabled: true                    # Enable pygame dashboard - pygame 대시보드 활성화
  window_size: [400, 300]          # [width, height] - 창 크기
  update_rate: 30                  # Hz - 업데이트 주파수

logging:
  # Logging configuration - 로깅 설정
  level: "INFO"                    # DEBUG, INFO, WARNING, ERROR - 로그 레벨
  file_logging: true               # Enable log files - 파일 로깅 활성화
  console_logging: true            # Enable console output - 콘솔 출력 활성화
  
  files:
    controller: "controller_rpi/controller.log"
    vehicle: "vehicle_rpi/vehicle.log"